educa/chat/urls.py
from django.urls import path
from . import views

app_name = "chat"
urlpatterns = [
    path("room/<int:course_id>/", views.course_chat_room, name="course_chat_room"),
]

educa/educa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from courses.views import CourseListView

urlpatterns = [
    # path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    # path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", include("account.urls")),
    path("account/", include("account.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("admin/", admin.site.urls),
    path("course/", include("courses.urls")),
    path("", CourseListView.as_view(), name="course_list"),
    path("students/", include("students.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("api/", include("courses.api.urls", namespace="api")),
    path("chat/", include("chat.urls", namespace="chat")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

educa/students/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views
from courses.views import StudentContentCreateUpdateView
from courses.views import StudentContentDeleteView


urlpatterns = [
    path(
        "register/",
        views.StudentRegistrationView.as_view(),
        name="student_registration",
    ),
    path(
        "enroll-course/",
        views.StudentEnrollCourseView.as_view(),
        name="student_enroll_course",
    ),
    path("courses/", views.StudentCourseListView.as_view(), name="student_course_list"),
    # path(
    #     "course/<pk>/",
    #     cache_page(60 * 15)(views.StudentCourseDetailView.as_view()),
    #     name="student_course_detail",
    # ),
    # path(
    #     "course/<pk>/<module_id>/",
    #     cache_page(60 * 15)(views.StudentCourseDetailView.as_view()),
    #     name="student_course_detail_module",
    # ),Now I
    path(
        "course/<pk>/",
        views.StudentCourseDetailView.as_view(),
        name="student_course_detail",
    ),
    path(
        "course/<pk>/<module_id>/",
        views.StudentCourseDetailView.as_view(),
        name="student_course_detail_module",
    ),
    path(
        "course/<pk>/<int:module_id>/content/<str:model_name>/<int:id>/delete/",
        StudentContentDeleteView.as_view(),
        name="student_content_delete",
    ),
    path(
        "course/<pk>/<int:module_id>/content/<str:model_name>/create/",
        StudentContentCreateUpdateView.as_view(),
        name="student_content_create",
    ),
    path(
        "students/module/<int:module_id>/content/<int:pk>/",
        views.StudentContentDetailView.as_view(),
        name="student_content_detail",
    ),
]

educa/students/models.py
from django.db import models

# Create your models here.

educa/students/forms.py
from django import forms
from courses.models import Course


class CourseEnrollForm(forms.Form):
    course = forms.ModelChoiceField(
        queryset=Course.objects.none(), widget=forms.HiddenInput
    )

    def __init__(self, *args, **kwargs):
        super(CourseEnrollForm, self).__init__(*args, **kwargs)
        self.fields["course"].queryset = Course.objects.all()

educa/students/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.shortcuts import render
from django.views.generic.edit import CreateView, FormView
from django.views.generic.list import ListView
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.shortcuts import get_object_or_404, redirect
from courses.models import Course
from .forms import CourseEnrollForm
from courses.models import Content


class StudentRegistrationView(CreateView):
    template_name = "students/student/registration.html"
    form_class = UserCreationForm
    success_url = reverse_lazy("student_course_list")

    def form_valid(self, form):
        result = super().form_valid(form)
        cd = form.cleaned_data
        user = authenticate(username=cd["username"], password=cd["password1"])
        login(self.request, user)
        return result


class StudentEnrollCourseView(LoginRequiredMixin, FormView):
    course = None
    form_class = CourseEnrollForm

    def form_valid(self, form):
        self.course = form.cleaned_data["course"]
        self.course.students.add(self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("student_course_detail", args=[self.course.id])


class StudentCourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = "students/course/list.html"

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(students__in=[self.request.user])


# class StudentCourseDetailView(LoginRequiredMixin, DetailView):
#     model = Course
#     template_name = "students/course/detail.html"

#     def get_queryset(self):
#         qs = super().get_queryset()
#         return qs.filter(students__in=[self.request.user])

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         # get course object
#         course = self.get_object()
#         if "module_id" in self.kwargs:
#             # get current module
#             context["module"] = course.modules.get(id=self.kwargs["module_id"])
#         else:
#             # get first module
#             context["module"] = course.modules.all()[0]
#         return context


@method_decorator(never_cache, name="dispatch")
class StudentCourseDetailView(LoginRequiredMixin, DetailView):
    model = Course
    template_name = "students/course/detail.html"

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(students__in=[self.request.user])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Get course object
        course = self.get_object()
        if "module_id" in self.kwargs:
            # Get current module
            module = course.modules.get(id=self.kwargs["module_id"])
        else:
            # Get first module
            module = course.modules.first()

        context["module"] = module

        # Separate instructor and student content
        instructor_content = module.contents.filter(owner__groups__name="Instructors")
        # student_content = module.contents.filter(owner__in=course.students.all())
        student_content = module.contents.filter(owner=self.request.user)

        context["instructor_content"] = instructor_content
        context["student_content"] = student_content

        # Check if the user is enrolled in the course
        if self.request.user in course.students.all():
            context["can_upload"] = True
        else:
            context["can_upload"] = False

        return context


class StudentContentDetailView(LoginRequiredMixin, DetailView):
    model = Content
    template_name = "students/course/content_detail.html"

    def get_queryset(self):
        print("URL Parameters:", self.kwargs)
        # Ensure students can only view their own uploaded content
        qs = super().get_queryset()
        return qs.filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

educa/students/templates/students/course/content_detail.html
{% extends "base.html" %}

{% block title %}{{ object.item.title }}{% endblock %}

{% block content %}
  <h1>{{ object.item.title }}</h1>
  <p>Uploaded on: {{ object.item.created|date:"F j, Y, g:i a" }}</p>
  <div class="content-body">
    {{ object.item.render|safe }}
  </div>
  <p>
    <a href="{% url 'student_course_detail_module' object.module.course.id object.module.id %}">
      Back to Module
    </a>
  </p>
{% endblock %}

educa/students/templates/students/course/detail.html
{% extends "base.html" %}
{% load model_name %}
{% block title %}
  {{ object.title }}
{% endblock %}
{% block content %}
  <h1>{{ module.title }}</h1>
  <div class="contents">
    <h3>Modules</h3>
    <ul id="modules">
      {% for m in object.modules.all %}
        <li data-id="{{ m.id }}" {% if m == module %}class="selected"{% endif %}>
          <a href="{% url "student_course_detail_module" object.id m.id %}">
            <span>
              Module <span class="order">{{ m.order|add:1 }}</span>
            </span>
            <br>
            {{ m.title }}
          </a>
        </li>
      {% empty %}
        <li>No modules yet.</li>
      {% endfor %}
    </ul>
    <h3>
      <a href="{% url "chat:course_chat_room" object.id %}">Course chat room</a>
    </h3>
  </div>

  <!-- Instructor Content Section -->
  <div class="module">
    <h3>Module Content</h3>
    {% for content in instructor_content %}
      <div class="content-item">
        <h2>{{ content.item.title }}</h2>
        <p>{{ content.item.render }}</p>
      </div>
    {% empty %}
      <p>No instructor content available.</p>
    {% endfor %}
  </div>
  

  <div class="module">
    <!-- Add Upload Section -->
    {% if can_upload %}
      <h3>Upload Your Work:</h3>
      <ul class="content-types">
          <li>
              <a href="{% url 'student_content_create' module.id 'text' %}">Text</a>
          </li>
          <li>
              <a href="{% url 'student_content_create' module.id 'image' %}">Image</a>
          </li>
          <li>
              <a href="{% url 'student_content_create' module.id 'video' %}">Video</a>
          </li>
          <li>
              <a href="{% url 'student_content_create' module.id 'file' %}">File</a>
          </li>
      </ul>
    {% endif %}
  </div>

  <!-- Student Content Section -->
  <div class="module">
    <h3>Your Work</h3>
    {% for content in student_content %}
      <div class="content-item">
        <a href="{% url 'student_content_detail' module.id content.id %}"><h2>{{ content.item.title }}</h2></a>
        <!-- <p>{% comment %} {{ content.item.render }} {% endcomment %}</p> -->
        <p>Uploaded on: {{ content.item.created|date:"F j, Y, g:i a" }}</p>
      </div>
    {% empty %}
      <p>You have no work uploaded.</p>
    {% endfor %}
  </div>

{% endblock %}

educa/students/templates/students/course/list.html
{% extends "base.html" %}
{% block title %}My courses{% endblock %}
{% block content %}
  <h1>My courses</h1>
  <div class="module">
    {% for course in object_list %}
      <div class="course-info">
        <h3>{{ course.title }}</h3>
        <p><a href="{% url "student_course_detail" course.id %}">
        Access contents</a></p>
      </div>
    {% empty %}
      <p>
        You are not enrolled in any courses yet.
        <a href="{% url "course_list" %}">Browse courses</a>
        to enroll in a course.
      </p>
    {% endfor %}
  </div>
{% endblock %}